---
title: "stock price"
author: "Andrea Tang"
date: "2019年10月25日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/user/Desktop/python/2019_python/course_big data analysis")
```

```{r}
library(tidyverse)
library(readr)
library(VIM)
```

```{r}
set.seed(1234)
```


####1.knn imputation
####1.2 stock_A
* rememeber to remove price from df first
```{r}
# remove price value 
stock_A <- read.csv("A.csv") %>% select(-c(2))

na_cols <- colnames(stock_A)[colSums(is.na(stock_A)) > 0]
na_cols1 <- colnames(stock_A)[colSums(is.na(stock_A)) > 2000]
na_impute = c()
#only impute the columns with less then 2000 NAs
#learn: the opposite expression %in%
for (col in na_cols) {
  if (!(col %in% na_cols1))
    na_impute <- c(na_impute, col)
}

stock_A1 <- kNN(stock_A, variable = na_impute)
stock_A1_1 <- stock_A1 %>% select(-na_cols1) %>% select(c(1:98)) %>% select(-c( "A...AMORTIZATION.OF.DEFERRED.CHARG"))
#stock_A1_1 <- cbind(A, stock_A1_1)
saveRDS(stock_A1_1, file = "stockA.rds")
```
####1.2 stock_B
```{r}
stock_B <- read.csv("B.csv") %>% select(-c(2))

na_cols <- colnames(stock_B)[colSums(is.na(stock_B)) > 0]
na_cols1 <- colnames(stock_B)[colSums(is.na(stock_B)) > 2000]
na_impute = c()
#only impute the columns with less then 2000 NAs
#learn: the opposite expression %in%
for (col in na_cols) {
  if (!(col %in% na_cols1))
    na_impute <- c(na_impute, col)
}

stock_B1 <- kNN(stock_B, variable = na_impute)
stock_B1_1 <- stock_B1 %>% select(-na_cols1) %>% select(c(1:98)) %>% select(-c( "B...AMORTIZATION.OF.DEFERRED.CHARG"))
#stock_B1_1 <- cbind(B, stock_B1_1)
saveRDS(stock_B1_1, file = "stockB.rds")
```

####1.3 stock_C
```{r}
stock_C <- read.csv("C.csv") %>% select(-c(2))

na_cols <- colnames(stock_C)[colSums(is.na(stock_C)) > 0]
na_cols1 <- colnames(stock_C)[colSums(is.na(stock_C)) > 2000]
na_impute = c()
#only impute the columns with less then 2000 NAs
#learn: the opposite expression %in%
for (col in na_cols) {
  if (!(col %in% na_cols1))
    na_impute <- c(na_impute, col)
}

stock_C1 <- kNN(stock_C, variable = na_impute)
stock_C1_1 <- stock_C1 %>% select(-na_cols1) %>% select(c(1:99)) %>% select(-c("C...12M.FWD.FREE.CASH.FLOW.YLD....", "C...AMORTIZATION.OF.DEFERRED.CHARG"))

# only stock C has less than 2000NAs in "12M.FWD.FREE.CASH.FLOW.YLD", thus delete this column at last
saveRDS(stock_C1_1, file = "stockC.rds")
```

####1.4 stock_D
```{r}
stock_D <- read.csv("D.csv") %>% select(-c(2))

na_cols <- colnames(stock_D)[colSums(is.na(stock_D)) > 0]
na_cols1 <- colnames(stock_D)[colSums(is.na(stock_D)) > 2000]
na_impute = c()
#only impute the columns with less then 2000 NAs
#learn: the opposite expression %in%
for (col in na_cols) {
  if (!(col %in% na_cols1))
    na_impute <- c(na_impute, col)
}

stock_D1 <- kNN(stock_D, variable = na_impute)
stock_D1_1 <- stock_D1 %>% select(-na_cols1) %>% select(c(1:98)) %>% select(-c("D...12M.FWD.FREE.CASH.FLOW.YLD...."))
# stock_D1_1 <- cbind(D, stock_D1_1)
saveRDS(stock_D1_1, file = "stockD.rds")
```

##### delete not equivalent columns
```{r}
# D"AMORTIZATION.OF.DEFERRED.CHARG" more than 2000NAs, while others < 2000.
# Also, both C & D have less than 2000NAs in "12M.FWD.FREE.CASH.FLOW.YLD".
```


####1.5 stock_E
```{r}
stock_E <- read.csv("E.csv") %>% select(-c(2))
E <- read.csv("E.csv") %>% select(c("E"))
na_cols <- colnames(stock_E)[colSums(is.na(stock_E)) > 0]

na_cols1 <- colnames(stock_E)[colSums(is.na(stock_E)) > 2000]
na_impute = c()
#only impute the columns with less then 2000 NAs
#learn: the opposite expression %in%
for (col in na_cols) {
  if (!(col %in% na_cols1))
    na_impute <- c(na_impute, col)
}

stock_E1 <- kNN(stock_E, variable = na_impute)
stock_E1_1 <- stock_E1 %>% select(-na_cols1) %>% select(c(1:87)) 
saveRDS(stock_E1_1, file = "stockE.rds")
```

####2. regularization
```{r}
stock_A_scale <- as.data.frame(scale(stock_A1_1, center = TRUE, scale = TRUE))
stock_B_scale <- as.data.frame(scale(stock_B1_1, center = TRUE, scale = TRUE))
stock_C_scale <- as.data.frame(scale(stock_C1_1, center = TRUE, scale = TRUE))
stock_D_scale <- as.data.frame(scale(stock_D1_1, center = TRUE, scale = TRUE))
stock_E_scale <- as.data.frame(scale(stock_E1_1, center = TRUE, scale = TRUE))

```
####3. combine a-d dataframes
```{r}
colnames(stock_A_scale)=colnames(stock_B_scale)=colnames(stock_C_scale) = colnames(stock_D_scale)
bind_df <- stock_A_scale %>% bind_rows(stock_B_scale, stock_C_scale, stock_D_scale)

# deselect columns that can't be scaled
D_one <- read.csv("stock_Done11.csv")
DD <- colnames(D_one)
bind_df <- bind_df %>% select(DD)

#比對stock_E_scale和bind_df的欄位，將不同者刪去
stock_E_scale <- stock_E_scale %>% select(-c("E...E...MARKET.VALUE", "E...E", "E...E...TURNOVER.BY.VOLUME" , "E...12M.FWD.PE.vs.SECTOR", "E...PREFERRED.STOCK", "E...NET.CASH.FLOW.OPERATING.ACTIVS", "E...NET.SALES.OR.REVENUES", "E...INTEREST.EXPENSE.ON.DEBT", "E...PREFERRED.DIVIDEND.REQUIREMENT"))
bind_df <- bind_df %>% select(-c("D...AMORTIZATION.INTANGIBLE.ASSETS", "D...SELLING..GENERAL...ADMINISTRAT", "D...RESEARCH...DEVELOPMENT"))
colnames(stock_E_scale) = colnames(bind_df)
bind_df1 <- bind_df %>% bind_rows(stock_E_scale)

write.csv(bind_df1, file = "stock_knn.csv",row.names = FALSE)
```


